-- V1: Estructura inicial (editoriales, generos, libros)
-- Compatible con H2 y mapeos JPA/Hibernate actuales

CREATE TABLE editoriales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    CONSTRAINT uk_editoriales_nombre UNIQUE (nombre)
);

CREATE TABLE generos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    CONSTRAINT uk_generos_nombre UNIQUE (nombre)
);

CREATE TABLE libros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tittle VARCHAR(150) NOT NULL,
    author VARCHAR(150) NOT NULL,
    isbn VARCHAR(20),
    fecha_publicacion DATE,
    precio DOUBLE PRECISION NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    editorial_id BIGINT NOT NULL,

    CONSTRAINT uk_libros_isbn UNIQUE (isbn),
    CONSTRAINT fk_libros_editoriales
        FOREIGN KEY (editorial_id)
        REFERENCES editoriales (id)
);
