-- V1: Creacion de las tablas principales del sistema LibroTech

CREATE TABLE editoriales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    direccion VARCHAR(500) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    fundado_en INT
);

CREATE TABLE generos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500),
    CONSTRAINT uk_generos_nombre UNIQUE (nombre)
);

CREATE TABLE libros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(200) NOT NULL,
    isbn VARCHAR(20),
    fecha_publicacion DATE NOT NULL,
    precio DOUBLE PRECISION,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    editorial_id BIGINT NOT NULL,

    CONSTRAINT uk_libros_isbn UNIQUE (isbn),
    CONSTRAINT fk_libro_editorial
        FOREIGN KEY (editorial_id)
        REFERENCES editoriales (id)
);
